"""user

Revision ID: a68d4b04e7f5
Revises: 
Create Date: 2019-03-04 02:41:29.040508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a68d4b04e7f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rol')
    op.drop_index('ix_user_username', table_name='user')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'rol_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('rol_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'user', 'rol', ['rol_id'], ['id'])
    op.create_index('ix_user_username', 'user', ['nombre'], unique=1)
    op.create_table('rol',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=40), nullable=False),
    sa.Column('rol_email', sa.VARCHAR(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
